# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eb8d5271a32c1571d6d1119997cd2b1833b24597703f89b7fceababfd75c69d87de5e5bba002bcd51bdc2f20a258e5072d1c302d3e524c173ce7cb72fc9ba4e

test:
  secret_key_base: 20701e3a96278cd3cea296f37e8f7ab9c61a5914bddb9a88fda3a0a5c587e91f26c0cc97335e986babcf3d7a6f3c7a683ac9ddb185fc505e49ff39566ca49c15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
